### ISSUE TITLE
Error r:603

### ISSUE THREAD

**Issue by jesnstevens** [slu-soc5050/Week-06#1]
Hi @chris-prener, 

I'm not sure if I'm forgetting a step or what but when trying to run my master do-file for problem set 04 I keep coming across error 603. 

log using "$projName/$projName.txt", text replace
(note: file /Users/NStevens/Documents/SLU/SOC5050/Working/Problem Set 04/Problem
>  Set 04.txt not found)
file /Users/NStevens/Documents/SLU/SOC5050/Working/Problem Set 04/Problem Set
    04.txt could not be opened

Hope you're having an enjoyable weekend. 
Thanks,
Jes

**Comment by chris-prener** [comment]
Can you attach your do-file to a comment here so I can take a look? Just the master file will do for right now.

**Comment by jesnstevens** [comment]
I've attached the master file. It wouldn't allow the stata file to be uploaded. If a txt version would be better I can try to save it as that kind of file instead of a pdf. 

[masterCopy.pdf](https://github.com/slu-soc5050/Week-06/files/505128/masterCopy.pdf)

**Comment by chris-prener** [comment]
Hey @jesnstevens , thanks for the code. Can you try taking the spaces out of your project name? Make it ps04 or problemSet04 or something similar. Let me know if that helps. 

The specific error code you mentioned is an ambiguous one - typically refers to an issue with the OS. 

@chris-prener

**Comment by jesnstevens** [comment]
Thanks @chris-prener.  That worked. I had a feeling it was something that I was just looking over. I appreciate the help!

**Comment by chris-prener** [comment]
Great news, @jesnstevens! Glad it worked. Try to avoid spaces in filenames at all costs when dealing with Stata, R, and other analysis packages.
