### ISSUE TITLE
question about markdoc

### ISSUE THREAD

**Issue by jesnstevens** [slu-soc5050/Week-06#2]
Hi @chris-prener,

So in my markdoc file, after running the master do file, it doesn't seem to be picking up any of the comments that I've left in my analysis file. Is there a way to troubleshoot this or should I just copy and paste the comments into the final edits of my markdoc file? 

Thanks, 
@jesnstevens

**Comment by chris-prener** [comment]
Hey @jesnstevens , What is in the comments? Are those your answers to questions or something else? 

@chris-prener

**Comment by jesnstevens** [comment]
@chris-prener, they are the answers to the questions. Maybe I'm just not remembering that I copied that portion into markdoc in the other problem sets? 

@jesnstevens

**Comment by chris-prener** [comment]
@jesnstevens - remember to fence your answers using the Markdoc commands `/***` (before your narrative) and `***/` (after your narrative) *instead* of using Stata comments. That way, your answers will get inserted into the body of your document.

cheers,
@chris-prener

**Comment by jesnstevens** [comment]
@chris-prener,  I have included those that's where I'm confused as to why it isn't being picked up. 

Thanks, 
@jesnstevens 

[analysis copy.pdf](https://github.com/slu-soc5050/Week-06/files/505245/analysis.copy.pdf)

**Comment by chris-prener** [comment]
Thanks for the code @jesnstevens. More questions:

  1. Do you get any errors when it executes? 
  2. Does the Markdown file get generated?
  3. Is the header in there but no answers to questions?

**Comment by jesnstevens** [comment]
@chris-prener, 

It executes well, no errors. 
The markdown file does get generated. 
The header is present but correct there are no answers. 

This is the file generated. 

[ProblemSet04-markdocCopy.pdf](https://github.com/slu-soc5050/Week-06/files/505255/ProblemSet04-markdocCopy.pdf)

**Comment by chris-prener** [comment]
@Jesnstevens - try placing the Markdoc fence commands on their own lines and see if this resolves the issue!

@Chris-prener

**Comment by jesnstevens** [comment]
Hey @chris-prener, that solved the problem! Thanks again for the help.
